In [1]:
import numpy as np
from labfuns import *

In [3]:
X, labels = genBlobs(centers=5)
print(X)
print(labels)

[[ 1.36069966  0.74802912]
 [-3.27894024  9.89995288]
 [ 0.58894326  4.00148458]
 [-0.97373942  6.94454493]
 [ 2.43169305 -0.20173713]
 [ 0.62835793  4.4601363 ]
 [-2.16434104  2.52061045]
 [-0.65392827  4.76656958]
 [ 0.73240494  2.87562511]
 [ 1.956815    0.23418537]
 [ 2.11567076  3.06896151]
 [ 3.18190344 -0.18226785]
 [ 7.01769098 -3.35367647]
 [-2.34026827  1.45145793]
 [ 0.30380963  3.94423417]
 [ 0.829832    1.74202664]
 [-3.06770103  2.98114426]
 [-1.36641982  7.15528181]
 [-1.10630261  7.5161316 ]
 [ 2.41163392  1.60423683]
 [-2.37508158  7.10478226]
 [-2.47135027  2.50783257]
 [ 2.47034915  4.09862906]
 [-1.63313558  7.9298116 ]
 [ 8.58924431 -0.67161883]
 [ 3.92282648  1.80370832]
 [-1.38420548  8.97235138]
 [ 1.05566092  6.77544419]
 [ 9.08260172 -2.72601914]
 [-1.94030562  9.37183707]
 [ 2.18217961  1.29965302]
 [-2.17052242  0.69447911]
 [-0.07228289  2.88376939]
 [ 0.34194798  3.94104616]
 [-1.37039748  3.1500633 ]
 [ 2.15504965  4.12386249]
 [10.63778706 -3.02061881]
 

In [28]:
classes = np.unique(labels)
idx = np.where(labels == 1)

xlc = X[idx,:]
mean_list = []
for i in range(Ndims):
    mean = np.sum(xlc[:,i])/len(idx)
    mean_list.append(mean) 

print(xlc)
print(mean_list)

[[[ 1.36069966  0.74802912]
  [ 2.43169305 -0.20173713]
  [ 1.956815    0.23418537]
  [ 3.18190344 -0.18226785]
  [ 0.829832    1.74202664]
  [ 2.41163392  1.60423683]
  [ 3.92282648  1.80370832]
  [ 2.18217961  1.29965302]
  [ 1.62011397  2.74692739]
  [ 1.98702592  2.61100638]
  [ 3.97820955  2.37817845]
  [ 2.22194102  1.5326951 ]
  [ 1.78726415  1.70012006]
  [ 3.93841822 -0.4500954 ]
  [ 0.78478252  1.86706037]
  [ 2.63185834  0.6893649 ]
  [ 1.55723507  2.82719571]
  [ 0.56400993  1.33705536]
  [ 1.19404184  2.80772861]
  [ 2.2635425   1.8743027 ]
  [ 1.28535145  1.43691285]
  [ 0.73936011  0.43607906]
  [ 3.00251949  0.74265357]
  [ 1.1424453   2.01467995]
  [ 2.66934689  1.81987033]
  [ 1.05505217 -0.64710744]
  [ 1.3105127   0.07122512]
  [ 2.3535057   2.22404956]
  [ 4.4384123   1.84214315]
  [ 1.38093486  0.92949422]
  [ 0.90779887  0.45984362]
  [ 2.45127423 -0.19539785]
  [ 2.72756228  1.3051255 ]
  [ 1.65209057  2.12010873]
  [ 1.64164854  0.15020885]
  [ 0.88214412  2.84

In [18]:
def mlParams(X, labels, W=None):
    assert(X.shape[0]==labels.shape[0])
    Npts,Ndims = np.shape(X)
    classes = np.unique(labels)
    Nclasses = np.size(classes)

    mu = np.zeros((Nclasses,Ndims))

    # TODO: fill in the code to compute mu and sigma!
    # ==========================
    for jdx, c in enumerate(classes):
        idx = np.where(labels == c)[0] 
        xlc = X[idx,:]
        mean_1 = np.mean(xlc[:, 0])  # 一列目の平均
        mean_2 = np.mean(xlc[:, 1])  # 二列目の平均

        mu[jdx] = [mean_1, mean_2]

    return mu

mu = mlParams(X, labels)
print(mu)

[[ 0.85337542  4.25688639]
 [ 2.05447901  1.32445001]
 [-1.56012838  2.70902796]
 [-1.48683466  7.9476099 ]
 [ 9.14794457 -2.61667701]]


In [19]:
Npts,Ndims = np.shape(X)
classes = np.unique(labels)
Nclasses = np.size(classes)
sigma = np.zeros((Nclasses,Ndims,Ndims))

for jdx, c in enumerate(classes):
        idx = np.where(labels == c)[0] # Vector of length C of indices for a given label class c
        xlc = X[idx, :] # Matrix  C x d with samples in the class c
        cov = np.cov(xlc.T)
        sigma[jdx] = cov

print(sigma)

[[[ 1.11798347 -0.0699714 ]
  [-0.0699714   0.92820965]]

 [[ 0.98306476 -0.08496186]
  [-0.08496186  0.97806907]]

 [[ 0.90064415  0.05975208]
  [ 0.05975208  0.82896233]]

 [[ 0.83451771 -0.17768215]
  [-0.17768215  1.02394889]]

 [[ 1.08940283  0.01734671]
  [ 0.01734671  0.71474629]]]


In [ ]:
def mlParams(X, labels, W=None):
    assert(X.shape[0]==labels.shape[0])
    Npts,Ndims = np.shape(X)
    classes = np.unique(labels)
    Nclasses = np.size(classes)

    mu = np.zeros((Nclasses,Ndims))
    sigma = np.zeros((Nclasses,Ndims,Ndims))

    # TODO: fill in the code to compute mu and sigma!
    # ==========================
    for jdx, c in enumerate(classes):
        idx = np.where(labels == c)[0] 
        xlc = X[idx,:]
        mean_1 = np.mean(xlc[:, 0]) 
        mean_2 = np.mean(xlc[:, 1]) 

        mu[jdx] = [mean_1, mean_2]


    for jdx, c in enumerate(classes):
        idx = np.where(labels == c)[0] # Vector of length C of indices for a given label class c
        xlc = X[idx, :] # Matrix  C x d with samples in the class c
        cov = np.cov(xlc.T)
        sigma[jdx] = cov
    # ==========================

    return mu, sigma

In [ ]:
labels = [1,2,1,3,2,1]

classes = np.unique(labels)
Nclasses = np.size(classes)

prior = np.zeros((Nclasses,1))

for jdx, i in enumerate(classes):
    idx = np.where(labels == i)[0]
    prior[jdx] = len(idx)/len(labels)

print(prior)


In [5]:
from labfuns import *

X, y, pcams = fetchDataset('iris')
print(X)
print(X.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.